#eureka 注册中心
server:
  port: 8761

eureka:
  instance:
    hostname: peer1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka/   #带账号方式登陆首页
      #defaultZone: http://localhost:8761/eureka/  匿名访问首页
    
  #server:
    #关闭自我保护功能
    #enable-self-preservation: false
    #清理服务器, 即扫描失效服务的间隔时间（缺省为60*1000ms）
    #eviction-interval-timer-in-ms: 5000 
      
spring:  security:    user:      password: password123     #配置登陆密码 password123      name: user                #配置登陆帐号 user 
  application:
    name: eureka-instance
