server:
  port: 8777

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
      
spring:
  application:
    name: service-turbine
    
management:  endpoints:    web:      cors:        allowed-origins: "*"        allowed-methods: "*"      exposure:        include: "*"

turbine:  app-config: service-hystrix,service-hystrix-turbine
  aggregator:    cluster-config: default  cluster-name-expression: new String("default")
  combine-host: true
  instanceUrlSuffix:
    default: actuator/hystrix.stream
  
        

