#eureka 服务提供者
server:
  port: 20000

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # 将Instance ID设置成IP:端口的形式
    lease-renewal-interval-in-seconds: 5             # 心跳时间，每隔几s发送心跳到eureka server
    lease-expiration-duration-in-seconds: 10      # #10s内没有收到客户端的心跳，则开始清理失效节点
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://user:password123@${eureka.instance.hostname}:8761/eureka/ 注册到带帐号的eureka服务上方式
    registry-fetch-interval-seconds: 5  #表示eureka client间隔多久去拉取服务注册信息
      
spring:
  application:
    name: servet-gateway-application             # 首页application 名字
    
management:
  endpoints:
    web:
      exposure:
        include: service-registry    #优雅的下线微服务的方式
