# config server 服务中心
server:
  port: 8774
  
spring:  zipkin:    base-url: http://localhost:9411
  application:
    name: config-sleuth
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
            
