#eureka 服务提供者
server:
  port: 8762

eureka:
  instance:
    hostname: localhost
    instance-id: eureka-server-provided
    lease-renewal-interval-in-seconds: 5             # 心跳时间，每隔几s发送心跳到eureka server
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://user:password123@${eureka.instance.hostname}:8761/eureka/ 注册到带帐号的eureka服务上方式
    registry-fetch-interval-seconds: 5  #表示eureka client间隔多久去拉取服务注册信息
      
spring:
  application:
    name: eureka-client
