server:
  port: 8763

eureka:
  instance:
    hostname: localhost
    instance-id: eureka-server-provided-2
    lease-renewal-interval-in-seconds: 5             # 心跳时间，即服务续约间隔时间（缺省为30s）
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    registry-fetch-interval-seconds: 5  #表示eureka client间隔多久去拉取服务注册信息
      
spring:
  application:
    name: eureka-client
