server:
  port: 8763

eureka:
  instance:
    hostname: localhost
    instance-id: eureka-server-provided-2
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
      
spring:
  application:
    name: eureka-client
